In [1]:
# importing numpy module
import numpy as np

### how list is passed into the numpy array to change it into  the array types.

In [3]:
a=np.array([5,6,7])      
a

array([5, 6, 7])

In [4]:
a.ndim                  # this will show the dimension of the array

1

In [5]:
a=np.array([[1,2],[3,4],[5,6]])       #2D array creation
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a.ndim

2

In [8]:
print(a.itemsize,"bytes")          # this shows the byte occupy by the datatype

4 bytes


In [9]:
a.shape                     #it will print the shape of the array

(3, 2)

In [10]:
np.ones((3,3))             #syntax    np.ones((shape of the required array))
                            #if  required only the ones.


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a1=np.arange(1,5)              #syntax:--->    np.arange(start,end,step)
print(a1)                        

[1 2 3 4]


In [16]:
a2=np.arange(1,10,2)
print(a2)

[1 3 5 7 9]


In [19]:
np.linspace(1,3)                      #linspace is used to print the linearly spaced value.

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [20]:
a=np.array([[1,2],[3,4],[5,6]])

In [21]:
a.reshape(2,3)                                  #reshape funtion is used to reshape the size of the array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.ravel()                                      #this funtion is used to flaten the array.

array([1, 2, 3, 4, 5, 6])

In [24]:
a.max()

6

In [25]:
a.min()

1

In [27]:
a.std()                       #std is used for the standard deviation.

1.707825127659933

In [29]:
a.sum(axis=1)                       #sum the element row wise.

array([ 3,  7, 11])

In [30]:
a.sum(axis=0)                    #sum the element column wise.

array([ 9, 12])

In [31]:
a1=np.array([[1,2],[3,4],[5,6]])

In [32]:
a2=np.array([[7,8,],[9,10],[11,12]])

In [33]:
a1+a2

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [34]:
a2-a1

array([[6, 6],
       [6, 6],
       [6, 6]])

In [35]:
a2*a1


array([[ 7, 16],
       [27, 40],
       [55, 72]])

## slicing in numpy array.

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[1,1]                                  #syntax:----> arrayname[row,column]

5

In [7]:
#now we have to find the elements [2,5,8]
a[:,1]

array([2, 5, 8])

In [10]:
# now we have to access the element[6,9]
a[1:,2]

array([6, 9])

In [16]:
# elements [4,5,6]
a[1:2]

array([[4, 5, 6]])

In [22]:
# elements to find out ----> [1,5,9]
a[:,2]

array([3, 6, 9])